-- ============================================================================
-- Supabase Schema for Kono Elm Encyclopedia (موسوعة كنوز العلم الإلكترونية)
-- ============================================================================

-- Create the search_logs table
CREATE TABLE IF NOT EXISTS search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL,
  results_count INTEGER,
  search_duration_ms INTEGER,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE search_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow inserts for search logs" ON search_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated reads for search logs" ON search_logs FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow service role full access" ON search_logs FOR ALL USING (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS idx_search_logs_created_at ON search_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_logs_query ON search_logs(query);

-- SEO Categories Table
CREATE TABLE IF NOT EXISTS seo_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- SEO Books Table
CREATE TABLE IF NOT EXISTS seo_books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  author TEXT,
  description TEXT,
  category TEXT,
  archive_id TEXT UNIQUE NOT NULL,
  seo_title TEXT,
  parts_count INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- SEO Authors Table
CREATE TABLE IF NOT EXISTS seo_authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE seo_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_authors ENABLE ROW LEVEL SECURITY;

-- Policies: Public Read
CREATE POLICY "Allow public read for seo_categories" ON seo_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read for seo_books" ON seo_books FOR SELECT USING (true);
CREATE POLICY "Allow public read for seo_authors" ON seo_authors FOR SELECT USING (true);

-- Policies: Service Role / Admin Write
CREATE POLICY "Allow service role full access for categories" ON seo_categories FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow service role full access for books" ON seo_books FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow service role full access for authors" ON seo_authors FOR ALL USING (auth.role() = 'service_role');

-- Search stats function
CREATE OR REPLACE FUNCTION get_search_stats(days INTEGER DEFAULT 7)
RETURNS TABLE (
  total_searches BIGINT,
  unique_queries BIGINT,
  avg_results_per_search FLOAT,
  most_popular_queries JSON
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT AS total_searches,
    COUNT(DISTINCT query)::BIGINT AS unique_queries,
    AVG(results_count)::FLOAT AS avg_results_per_search,
    (
      SELECT json_agg(json_build_object('query', query, 'count', cnt))
      FROM (
        SELECT query, COUNT(*) as cnt
        FROM search_logs
        WHERE created_at >= NOW() - (days || ' days')::INTERVAL
        GROUP BY query
        ORDER BY cnt DESC
        LIMIT 10
      ) AS top_queries
    )::JSON AS most_popular_queries;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
