-- ============================================================================
-- Supabase Schema for Huda Library Donation System
-- ============================================================================

-- 1. Create donation_settings table
CREATE TABLE IF NOT EXISTS donation_settings (
  id INT PRIMARY KEY DEFAULT 1,
  enabled BOOLEAN DEFAULT TRUE,
  show_button BOOLEAN DEFAULT TRUE,
  wallet_address TEXT NOT NULL DEFAULT 'TY1234567890HudaLibraryTRC20Address',
  currency TEXT NOT NULL DEFAULT 'USDT',
  network TEXT NOT NULL DEFAULT 'TRON (TRC-20)',
  qr_code TEXT DEFAULT '',
  title_ar TEXT NOT NULL DEFAULT 'ساهم في استمرار مكتبة الهدى',
  title_en TEXT NOT NULL DEFAULT 'Support Huda Library',
  description_ar TEXT NOT NULL DEFAULT 'مكتبة الهدى مشروع معرفي يهدف إلى إتاحة المصادر الإسلامية والكتب والمخطوطات للباحثين وطلاب العلم والقراء. دعمك يساعدنا على استمرار تشغيل المكتبة وتطويرها وإتاحة محتواها.',
  description_en TEXT NOT NULL DEFAULT 'Huda Library is a knowledge project aiming to make Islamic resources, books, and manuscripts accessible to researchers, students, and readers. Your support helps us continue operating, developing, and providing free access to content.',
  preset_amounts JSONB DEFAULT '[5, 10, 25, 50, 100]',
  explorer_url_template TEXT DEFAULT 'https://tronscan.org/#/address/{address}',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT single_row CHECK (id = 1)
);

-- Insert default row if not exists
INSERT INTO donation_settings (id, enabled, show_button, wallet_address, currency, network, title_ar, title_en, description_ar, description_en)
VALUES (
  1,
  TRUE,
  TRUE,
  'TY1234567890HudaLibraryTRC20Address',
  'USDT',
  'TRON (TRC-20)',
  'ساهم في استمرار مكتبة الهدى',
  'Support Huda Library',
  'مكتبة الهدى مشروع معرفي يهدف إلى إتاحة المصادر الإسلامية والكتب والمخطوطات للباحثين وطلاب العلم والقراء. دعمك يساعدنا على استمرار تشغيل المكتبة وتطويرها وإتاحة محتواها.',
  'Huda Library is a knowledge project aiming to make Islamic resources, books, and manuscripts accessible to researchers, students, and readers. Your support helps us continue operating, developing, and providing free access to content.'
)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS for donation_settings
ALTER TABLE donation_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read for donation_settings" ON donation_settings FOR SELECT USING (true);
CREATE POLICY "Allow service_role full access for donation_settings" ON donation_settings FOR ALL TO service_role USING (true) WITH CHECK (true);


-- 2. Create donations table
CREATE TABLE IF NOT EXISTS donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_hash TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USDT',
  network TEXT NOT NULL DEFAULT 'TRON (TRC-20)',
  amount NUMERIC(12, 2) DEFAULT 0,
  donor_name TEXT,
  donor_email TEXT,
  donor_message TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS for donations
ALTER TABLE donations ENABLE ROW LEVEL SECURITY;

-- Allow public to insert donation confirmation details
CREATE POLICY "Allow public insert for donations" ON donations FOR INSERT WITH CHECK (true);
-- Only service role (admin) can select or modify donations
CREATE POLICY "Allow service_role full access for donations" ON donations FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_donations_created_at ON donations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_status ON donations(status);
CREATE INDEX IF NOT EXISTS idx_donations_tx_hash ON donations(transaction_hash);
