-- SQL to create the search_logs table in Supabase
-- Run this SQL in your Supabase project's SQL Editor

-- Create the search_logs table
CREATE TABLE IF NOT EXISTS search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL,
  results_count INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security (optional)
ALTER TABLE search_logs ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow inserts (for the app)
CREATE POLICY "Allow inserts for search logs" ON search_logs
  FOR INSERT
  WITH CHECK (true);

-- Create a policy to allow selects (for analytics)
CREATE POLICY "Allow selects for search logs" ON search_logs
  FOR SELECT
  USING (true);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_search_logs_created_at ON search_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_logs_query ON search_logs(query);