-- ============================================================================
-- Supabase Schema for Kono Elm Encyclopedia (موسوعة كنوز العلم الإلكترونية)
-- ============================================================================
-- This SQL creates the necessary table for logging search operations.
-- Run this in your Supabase project's SQL Editor.
-- ============================================================================

-- Create the search_logs table
CREATE TABLE IF NOT EXISTS search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL,
  results_count INTEGER,
  search_duration_ms INTEGER,        -- Time taken for search in milliseconds
  user_agent TEXT,                    -- Browser/user agent information
  ip_address TEXT,                    -- Client IP address (optional)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security
ALTER TABLE search_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anonymous inserts (for the app)
CREATE POLICY "Allow inserts for search logs" ON search_logs
  FOR INSERT
  WITH CHECK (true);

-- Policy: Allow authenticated reads (for analytics)
CREATE POLICY "Allow authenticated reads for search logs" ON search_logs
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Policy: Allow service role full access (for admin)
CREATE POLICY "Allow service role full access" ON search_logs
  FOR ALL
  USING (auth.role() = 'service_role');

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_search_logs_created_at ON search_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_search_logs_query ON search_logs(query);
CREATE INDEX IF NOT EXISTS idx_search_logs_results_count ON search_logs(results_count);

-- ============================================================================
-- Enable Realtime (optional - for live updates)
-- ============================================================================
-- Uncomment the following line if you want real-time updates:
-- ALTER PUBLICATION supabase_realtime ADD TABLE search_logs;

-- ============================================================================
-- Create a function to get search statistics (optional)
-- ============================================================================
CREATE OR REPLACE FUNCTION get_search_stats(days INTEGER DEFAULT 7)
RETURNS TABLE (
  total_searches BIGINT,
  unique_queries BIGINT,
  avg_results_per_search FLOAT,
  most_popular_queries JSON
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT AS total_searches,
    COUNT(DISTINCT query)::BIGINT AS unique_queries,
    AVG(results_count)::FLOAT AS avg_results_per_search,
    (
      SELECT json_agg(json_build_object('query', query, 'count', cnt))
      FROM (
        SELECT query, COUNT(*) as cnt
        FROM search_logs
        WHERE created_at >= NOW() - (days || ' days')::INTERVAL
        GROUP BY query
        ORDER BY cnt DESC
        LIMIT 10
      ) AS top_queries
    )::JSON AS most_popular_queries;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;